--- 
:album_escapes: 
  `: `
  "@": "@"
  +: " "
  ",": ","
  "!": \!
  "-": "-"
  "\"": "&quot;"
  .: .
  "#": \#
  ":": "\\:"
  /: /
  $: $
  "{": "{"
  "[": "["
  ;: ;
  "%": "%"
  "|": "|"
  \: \\
  <: "&lt;"
  "&": 
  "}": "}"
  "]": "]"
  "=": 
  "'": "'"
  "~": "~"
  ^: ^
  ">": "&gt;"
  (: (
  _: _
  "?": "?"
  ): )
  "*": "*"
:image_escapes: 
  `: `
  "@": "@"
  +: +
  ",": ","
  "!": \!
  "-": "-"
  "\"": "&quot;"
  .: .
  "#": \#
  ":": "\\:"
  /: /
  $: $
  "{": "{"
  "[": "["
  ;: ;
  "%": "%"
  "|": "|"
  \: \\
  <: "&lt;"
  "&": "&amp;"
  "}": "}"
  "]": "]"
  "=": 
  "'": "'"
  "~": "~"
  ^: ^
  ">": "&gt;"
  (: (
  _: _
  "?": "?"
  ): )
  "*": "*"
